export const BookGenres = {
	FICTION: 'Художня',
	NON_FICTION: 'Наукова',
	FANTASY: 'Фантастика',
	MYSTERY: 'Детектив',
	ROMANCE: 'Роман',
	SCIENCE_FICTION: 'Наукова фантастика',
	HORROR: 'Жахи',
	THRILLER: 'Трилер',
	HISTORICAL_FICTION: 'Історична проза',
	POETRY: 'Поезія',
	DRAMA: 'Драма',
	ADVENTURE: 'Пригоди',
	BIOGRAPHY: 'Біографія',
	AUTOBIOGRAPHY: 'Автобіографія',
	CHILDRENS: 'Дитяча',
	YOUNG_ADULT: 'Молодіжна',
	COMICS: 'Комікс',
	FANTASTIC_PROSE: 'Фантастична проза',
	POPULAR_PSYCHOLOGY: 'Популярна психологія',
	POPULAR_SCIENCE: 'Науково-популярна',
	PHILOSOPHY: 'Філософія',
	CLASSICS: 'Класика',
	LITERARY_DETECTIVE: 'Літературний детектив',
	SATIRE: 'Сатира',
	MYSTIC: 'Містика',
	PROGRAMMING: 'Програмування',
	HISTORY: 'Історія',
	CULTURE_AND_ART: 'Культура та мистецтво',
	COOKING: 'Кулінарія',
	TRAVEL: 'Подорожі',
	POLITICS: 'Політика',
	HISTORICAL_DETECTIVE: 'Історичний детектив',
	MAGIC_AND_SORCERY: 'Магія і чарівництво',
	CHILDRENS_FANTASY: 'Фантастика для дітей',
	PSYCHOLOGICAL_THRILLER: 'Психологічний трилер',
	EPISTOLARY_NOVEL: 'Роман у листах',
	DIALOGUE_NOVEL: 'Ділоговий роман',
	MOVIE_NOVEL: 'Фільмовий роман',
}
